create table tb_users (id int8 generated by default as identity, email varchar(255), name varchar(255), primary key (id));
alter table if exists tb_users add constraint UK_grd22228p1miaivbn9yg178pm unique (email);
create table tb_users (id int8 generated by default as identity, email varchar(255), name varchar(255), primary key (id));
alter table if exists tb_users add constraint UK_grd22228p1miaivbn9yg178pm unique (email);
